# Site settings
title: The résumé of Mary Garifullina
author:
  address:
      street: 4 Your Street
      town: Faketown
      postcode: NG11 9BC
      country: United Kingdom
  email: garifullina.m@gmail.com
  name: Mary Garifullina
  title: Mary Garifullina
#   twitter_username: nternetinspired
#   github_username:  nternetinspired
  phone: +353 89 4899180
  repository: https://github.com/gmarry/cv
  website: https://github.com/gmarry/cv
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "/cv/" # the subpath of your site, e.g. /blog/
url: "http://nternetinspired.github.io" # the base hostname & protocol for your site

# Compress html
compress_html:
  clippings: ['!--', html, head, title, base, link, meta, style, body, article, section, nav, aside, h1, h2, h3, h4, h5, h6, hgroup, header, footer, address, p, hr, blockquote, ol, ul, li, dl, dt, dd, figure, figcaption, main, div, table, caption, colgroup, col, tbody, thead, tfoot, tr, td, th]
  endings: [html, head, body, li, dt, dd, p, rt, rp, optgroup, option, colgroup, caption, thead, tbody, tfoot, tr, td, th]

# Build settings
markdown: kramdown
sass:
    style: :compressed
